#!/bin/bash

# Camera Exclusive Setup - pipewire カメラモジュール競合解決
# Raspberry Pi のカメラサービス専用化スクリプト

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

log_info() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [INFO] $1"
}

log_warn() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [WARN] $1"
}

log_error() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [ERROR] $1"
}

check_pipewire_camera_packages() {
    log_info "Checking for pipewire camera packages..."

    local packages_found=0

    if dpkg -l | grep -q "pipewire-libcamera"; then
        log_warn "Found pipewire-libcamera package"
        packages_found=1
    fi

    if dpkg -l | grep -q "libspa-0.2-libcamera"; then
        log_warn "Found libspa-0.2-libcamera package"
        packages_found=1
    fi

    return $packages_found
}

remove_pipewire_camera_packages() {
    log_info "Removing pipewire camera packages..."

    # 競合するパッケージを削除
    sudo apt remove -y pipewire-libcamera libspa-0.2-libcamera 2>/dev/null || true

    # パッケージを hold 状態にして将来のインストールを防止
    echo "pipewire-libcamera hold" | sudo dpkg --set-selections 2>/dev/null || true
    echo "libspa-0.2-libcamera hold" | sudo dpkg --set-selections 2>/dev/null || true

    log_info "Pipewire camera packages removed and held"
}

setup_apt_pinning() {
    log_info "Setting up apt pinning to prevent pipewire camera package installation..."

    sudo mkdir -p /etc/apt/preferences.d

    sudo tee /etc/apt/preferences.d/pipewire-camera-block > /dev/null << 'EOF'
# Block pipewire camera packages to prevent camera device conflicts
# Generated by coordinate-recorder setup

Package: pipewire-libcamera
Pin: release *
Pin-Priority: -1

Package: libspa-0.2-libcamera
Pin: release *
Pin-Priority: -1
EOF

    log_info "Apt pinning configuration created"
}

verify_camera_exclusivity() {
    log_info "Verifying camera device exclusivity..."

    # pipewire プロセスがカメラデバイスを使用していないことを確認
    if lsof /dev/video* 2>/dev/null | grep -q pipewire; then
        log_warn "Pipewire is still using camera devices"
        log_info "Restarting pipewire services..."

        # pipewire を再起動してカメラデバイスを解放
        sudo systemctl --user restart pipewire.service 2>/dev/null || true
        sudo systemctl restart pipewire 2>/dev/null || true

        sleep 3

        if lsof /dev/video* 2>/dev/null | grep -q pipewire; then
            log_warn "Pipewire still using camera devices after restart"
            return 1
        fi
    fi

    log_info "Camera devices are available for exclusive use"
    return 0
}

main() {
    log_info "Starting camera exclusive setup..."

    # pipewire カメラパッケージのチェック
    if check_pipewire_camera_packages; then
        remove_pipewire_camera_packages
    else
        log_info "No conflicting pipewire camera packages found"
    fi

    # apt pinning 設定
    setup_apt_pinning

    # カメラデバイスの排他性確認
    if verify_camera_exclusivity; then
        log_info "✅ Camera exclusive setup completed successfully"
    else
        log_warn "⚠️ Camera exclusive setup completed with warnings"
    fi

    log_info "Camera service should now start without pipewire conflicts"
}

# スクリプトが直接実行された場合のみ main を実行
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
